name: flipfx_widgets
description: A Flutter package for creating customizable flip animations between two widgets.
version: 0.0.2
homepage: https://github.com/iamtvirani/flipfx_widgets
repository: https://github.com/iamtvirani/flipfx_widgets

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
